### ISSUE TITLE
Why would the rate be biased against a binomial law ?

### ISSUE THREAD

**Issue by callicles** [gitlinks/notebooks#1]
You use

``` py
def biaised_rate(rates):
    if rates == []:
        return np.random.binomial(5, AVERALL_AVERAGE_RATE)
    else:
        return np.random.binomial(5, np.mean(rates)/5.1) #5.1 to avoid p=1
```

I don't understand why you use a binomial law.

**Comment by pocman** [comment]
L'objectif était de générer de manière aléatoire des repos avec des bonnes notes et d'autres avec des mauvaises.

Une meilleur approche : à la génération des repos, on tire la note moyenne de ce repos. On utilise ensuite cette note comme biais pour les rates des utilisateurs.

**Comment by callicles** [comment]
That sounds better.

**Comment by callicles** [comment]
I guess that's done
