### ISSUE TITLE
Should we use MCMC to estimate the score ?

### ISSUE THREAD

**Issue by pocman** [gitlinks/notebooks#2]
The weighted average of ratings is not a great estimate of the repo score when the number of ratings is low.
We could use Mcmc to estimate the distribution of ratings using a prior (every ratings of every repo) and observables (the rates for this specific repo).

Going further, we could model the precision of an user (its average error) and use this precision to weight ratings. This could satisfy the "Looking back, people that initialy rated a project accurately should be rewarded by Karma."

**Comment by callicles** [comment]
Looks very promising :)

You could implement that kind of solution in the notebook in a function `scoreUsingMCMC` so that we can compare and see the difference.

**Comment by pocman** [comment]
J'ai testé ça semble assez complexe, mais je sais que c'est vraiment pratique.
