### ISSUE TITLE
Add historical trend of repo score evolution

### ISSUE THREAD

**Issue by callicles** [gitlinks/notebooks#3]
It would be nice to have the evolution of the rating over time (see if it converges according to the mean value decided at the initialization)

**Comment by pocman** [comment]
Première version sans l'évolution mais uniquement pour un nombre de vote donné : 86ec068609551166a3a0ad9c729c71dda552123a

**Comment by pocman** [comment]
![capture d ecran 2015-06-18 a 23 36 02](https://cloud.githubusercontent.com/assets/1695808/8242874/d334c5be-1612-11e5-82b6-dd586e5d7022.png)
